### ISSUE TITLE
download cottbus coordinates automated from overpass

### ISSUE THREAD

**Issue by blueonyx** [oklab-cottbus/streetnames-cb#1]
aus dem Protokoll:

## Overpass API

Mit der [Overpass API](https://overpass-turbo.eu/) kann man schnell und einfach bestimmte Merkmale von mit OpenStreetMap abfragen und darstellen:

Z.B. Abfrage der Stadtgrenze von Cottbus:
    
```
[out:json][timeout:25];
(
  node["place"="city"]({{bbox}}); 
  way["place"="city"]({{bbox}});
  relation["place"="city"]({{bbox}});
);
out body;
>;
out skel qt;
```

Wenn man es als GeoJSON exportiert kann man die Koordinaten extrahieren.

Die Overpass API kann auch mit einem R-Paket abgefragt werden. Hier ein Blogpost dazu: [Accessing OpenStreetMap data with R | Dominic Royé](https://dominicroye.github.io/en/2018/accessing-openstreetmap-data-with-r/)

**Comment by blueonyx** [comment]
alternative overpass query using "admin levels":

```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“admin_level=6”
*/
[out:json][timeout:25];
// gather results
(
// query part for: “admin_level=6”
relation["admin_level"="6"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by blueonyx** [comment]
other possibilities:

http://polygons.fr has export options for "polygon" as well as "geojson" (thanks @JensWinter)

the openstreetmap relation id for cottbus is 62430:

http://polygons.openstreetmap.fr/?id=62430
http://polygons.openstreetmap.fr/get_geojson.py?id=62430&params=0

another way to get shape files (thanks @TobRecke):

https://www.geofabrik.de/de/data/shapefiles.html

**Comment by AutomisationChris** [comment]
Possible Way to get Shape files https://ec.europa.eu/eurostat/de/web/gisco/geodata/reference-data/administrative-units-statistical-units/communes

**Comment by TobRCB** [comment]
Administrative areas 1:250 000 Germany shapefile:

https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-250-000-ebenen-stand-01-01-vg250-ebenen-01-01.html

Territorial units 1:250 000 Germany shapefile:
https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/nicht-administrative-gebietseinheiten/gebietseinheiten-1-250-000-ge250.html

**Comment by scholzling** [comment]
@TobRecke 

R snippet wfs-data cottbusser stadteile: mit Daten von https://cardo.cottbus.de/net3/public/IkxCms/Default.aspx?pgid=75
```R
library(gdalUtils)
library(rgdal)

dsn <- “WFS:https://cardo.cottbus.de/net3/public/ogc.ashx?NodeId=75&Service=WFS&Request=GetCapabilities&”

[1] “INFO: Open of WFS:https://cardo.cottbus.de/net3/public/ogc.ashx?NodeId=75&Service=WFS&Request=GetCapabilities&'" [2] " using driverWFS’ successful.”
[3] “Metadata:”
[4] " ABSTRACT=Dieser Datensatz enthält die Darstellung der 19 Ortsteile der Stadt Cottbus inkl. der Bezeichnung."
[5] " PROVIDER_NAME=Stadtverwaltung Cottbus"
[6] " TITLE=Ortsteile der Stadt Cottbus"
[7] “1: cls:L60 (title: Ortsteile)”

ogr2ogr(dsn, “L60.shp”, “L60”)

cb <- readOGR(“L60.shp”, “L60”, stringsAsFactors=FALSE)

class : SpatialPolygonsDataFrame
features : 19
extent : 449880, 465595.7, 5727053, 5746166 (xmin, xmax, ymin, ymax)
crs : +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
variables : 5
names : gml_id, flaechenar, name, pk_ortst, flaeche
min values : L60.1, Ortsteil, Branitz, 1, 1671504.84148069
max values : L60.9, Ortsteil, Willmersdorf, 19, 31466431.0579198

plot(cb)
```

**Comment by TobRCB** [comment]
#### R snippet cottbus street names street  classified according to city districts
```R
library(tidyverse)
library(osmdata)
library(sf)
library(gdalUtils)
library(rgdal)


# shapefile from WFS
dsn <- “WFS:https://cardo.cottbus.de/net3/public/ogc.ashx?NodeId=75&Service=WFS&Request=GetCapabilities&”
ogrinfo(dsn, so=TRUE)
ogr2ogr(dsn, “L60.shp”, “L60”)
cb <- readOGR(“L60.shp”, “L60”, stringsAsFactors=FALSE)


#### get osmdata
cbs<-getbb("Cottbus Germany")

streets <- getbb("Cottbus Germany") %>%
  opq() %>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", 
                            "secondary", "tertiary",
                            "residential", "living_street",
                              "unclassified",
                              "service", "footway")) %>%
  osmdata_sf()

#### crs transform
cb_4326 <-st_as_sf(cb) %>% st_transform(., crs = 4326)

#### subsets streets per district
s_per_q<-lapply(cb_4326$geometry, function(x) {streets$osm_lines[x,] })
names(s_per_q)<-cb_4326$name

#### controll-plot
plot(cb_4326$geometry)
sapply(s_per_q, function(x){
  Sys.sleep(1)
  plot(x, add=T)
  })

#### namelist
namelist<-sapply(s_per_q, function(x) 
  x$name[!is.na(x$name)] %>% unique(.) 
)
```

**Comment by TobRCB** [comment]
Done.
